### PR TITLE
Remove Cache Clearing to reduce CDN load on failing devices (EXPOSUREAPP-2405)

### LINKED ISSUE #1021: CAUSE: 3 Something went wrong. ApiException: 39508
This bug was mentioned many times due to various causes but this seems to be a new case.

- Android 10
- OnePlus 5T
- CWA 1.2.0
- Play Services 20.26.65
- EN version: 15202902003

Exposure checks log:

```
August 8, 2020 09:27 (key count: 740)
August 8, 2020 09:27 (key count: 825)
August 8, 2020 09:27 (key count: 595)
August 8, 2020 09:27 (key count: 1790)
August 8, 2020 09:27 (key count: 2290)
August 8, 2020 09:27 (key count: 2520)
August 8, 2020 09:27 (key count: 1575)
August 8, 2020 09:27 (key count: 1405)
August 8, 2020 09:27 (key count: 1385)
August 8, 2020 09:27 (key count: 1645)

August 9, 2020 09:27 (key count: 825)
August 9, 2020 09:27 (key count: 595)
August 9, 2020 09:27 (key count: 1790)
August 9, 2020 09:27 (key count: 2290)
August 9, 2020 09:27 (key count: 2520)
August 9, 2020 09:27 (key count: 1575)
August 9, 2020 09:27 (key count: 1405)
August 9, 2020 09:27 (key count: 1385)
August 9, 2020 09:27 (key count: 1645)
August 9, 2020 09:27 (key count: 2813)
August 9, 2020 09:27 (key count: 2415)
August 9, 2020 09:27 (key count: 3050)
August 9, 2020 09:27 (key count: 2210)
August 9, 2020 09:27 (key count: 1655)

August 10, 2020 09:27 (key count: 595)
August 10, 2020 09:27 (key count: 1790)
August 10, 2020 09:27 (key count: 2290)
August 10, 2020 09:27 (key count: 2520)
August 10, 2020 09:27 (key count: 1575)
August 10, 2020 09:27 (key count: 1405)
August 10, 2020 09:27 (key count: 1385)
August 10, 2020 09:27 (key count: 1645)
August 10, 2020 09:27 (key count: 2813)
August 10, 2020 09:27 (key count: 2415)
August 10, 2020 09:27 (key count: 3050)
August 10, 2020 09:27 (key count: 2210)
August 10, 2020 09:27 (key count: 1655)
August 10, 2020 09:27 (key count: 565)

August 11, 2020 09:28 (key count: 1790)
August 11, 2020 09:28 (key count: 2290)
August 11, 2020 09:28 (key count: 2520)
August 11, 2020 09:28 (key count: 1575)
August 11, 2020 09:28 (key count: 1405)
August 11, 2020 09:28 (key count: 1385)
August 11, 2020 09:28 (key count: 1645)
August 11, 2020 09:28 (key count: 2813)
August 11, 2020 09:28 (key count: 2415)
August 11, 2020 09:28 (key count: 3050)
August 11, 2020 09:28 (key count: 2210)
August 11, 2020 09:28 (key count: 1655)
August 11, 2020 09:28 (key count: 565)
August 11, 2020 09:28 (key count: 2380)

August 12, 2020 09:56 (key count: 2290)
August 12, 2020 09:56 (key count: 2520)
August 12, 2020 09:56 (key count: 1575)
August 12, 2020 09:56 (key count: 1405)
August 12, 2020 09:56 (key count: 1385)
August 12, 2020 09:56 (key count: 1645)
August 12, 2020 09:56 (key count: 2813)
August 12, 2020 09:56 (key count: 2415)
August 12, 2020 09:56 (key count: 3050)
August 12, 2020 09:56 (key count: 2210)
August 12, 2020 09:56 (key count: 1655)
August 12, 2020 09:56 (key count: 565)
August 12, 2020 09:56 (key count: 2380)
August 12, 2020 09:59 (key count: 2285)

August 13, 2020 07:47 (key count: 2520)
August 13, 2020 07:47 (key count: 1575)
August 13, 2020 07:47 (key count: 1405)
August 13, 2020 07:47 (key count: 1385)
August 13, 2020 07:47 (key count: 1645)
August 13, 2020 07:47 (key count: 2813)
August 13, 2020 07:47 (key count: 2415)
August 13, 2020 07:47 (key count: 3050)
August 13, 2020 07:47 (key count: 2210)
August 13, 2020 07:47 (key count: 1655)
August 13, 2020 07:47 (key count: 565)
August 13, 2020 07:47 (key count: 2380)
August 13, 2020 07:47 (key count: 2285)
August 13, 2020 07:47 (key count: 3800)

August 14, 2020 07:36 (key count: 1575)
August 14, 2020 07:36 (key count: 1405)
August 14, 2020 07:36 (key count: 1385)
August 14, 2020 07:36 (key count: 1645)
August 14, 2020 07:36 (key count: 2813)
August 14, 2020 07:36 (key count: 2415)
August 14, 2020 07:36 (key count: 3050)
August 14, 2020 07:36 (key count: 2210)
August 14, 2020 07:36 (key count: 1655)
August 14, 2020 07:36 (key count: 565)
August 14, 2020 07:36 (key count: 2380)
August 14, 2020 07:36 (key count: 2285)
August 14, 2020 07:36 (key count: 3800)
August 14, 2020 07:36 (key count: 3940)

August 14, 2020 09:36 (key count: 1575)
August 14, 2020 09:36 (key count: 1405)
August 14, 2020 09:36 (key count: 1385)
August 14, 2020 09:36 (key count: 1645)
August 14, 2020 09:36 (key count: 2813)
August 14, 2020 09:36 (key count: 2415)
```

---
Internal Tracking ID: EXPOSUREAPP-2213

### LINKED ISSUE #1119: Risikostatus wird nicht aktualisiert
Nach Update auf die neueste Version 1.3.0 keine Aktualisierung des Risikostatus. Auch nach aus- und wieder einschalten keine Änderung. 

Screenshot_20200905-090605_Corona-Warn

Smartphone: Samsung Galaxy A50
Screenshot_20200905-093034_Settings

---
Internal tracking ID: EXPOSUREAPP-2213

### PR DESCRIPTION
**Pull request by jakobmoellerdev**
This ideally needs to be accompanied by a way to clear the cache manually and a way to identify more root causes of Transaction Failures.

Signed-off-by: d067928 <jakob.moeller@sap.com>

This PR reduces the load on the CDN due to failing Transactions. We currently do not have this Rollback behavior on iOS and the initial reason for this was due to the fear of corrupt Key Packages. It can be tested by either manually inserting an error or provoking a transaction failure on other ways in the Key Retrieval Process.

### CODE REVIEW

File: Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CachedKeyFileHolder.kt [hunk 1]
```diff
@@ -97,20 +97,33 @@ object CachedKeyFileHolder {
...
                     missingDays
                         .map { getURLForDay(it) }
-                        .map { url -> async { url.createDayEntryForUrl() } }
+                        .map { url ->
+                            val cacheKey = url.generateCacheKeyFromString()
+                            try {
+                                async {
+                                    url.createDayEntryForUrl(cacheKey)
+                                }
+                            } catch (e: Exception) {
```
Comment (d4rken) [inline Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CachedKeyFileHolder.kt:112]: Hm, this doesn't work, the exception will be catched by `async`, not our try catch
We need to try catch inside the `async`.

Comment (d4rken) [reply Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CachedKeyFileHolder.kt:112]: If we catch inside the async, the errors happen async, and `failedEntryCacheKeys` needs to be threadsafe, i.e. LinkedConcurrentQueue or a Collections.synchronized list.

File: Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CachedKeyFileHolder.kt [hunk 2]
```diff
@@ -97,20 +97,33 @@ object CachedKeyFileHolder {
...
                 )
             }
             // execute the query plan
             try {
                 deferredQueries.awaitAll()
             } catch (e: Exception) {
+                Timber.v("${failedEntryCacheKeys.size} failed entries ")
                 // For an error we clear the cache to try again
-                keyCache.clear()
+                keyCache.clear(failedEntryCacheKeys)
```
Comment (d4rken) [inline Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CachedKeyFileHolder.kt:126]: `awaitAll` resumes after the first exception is thrown. If we have multiple failed `async` operations, we may already be calling `clear(failedEntryCacheKeys)`  while on another thread `failedEntryCacheKeys.add(cacheKey)` is executed.

So  we wouldn't clear all failed items.
I think we should not rethrow within `async` so that we wait for all operations to finish via `awaitAll`, then check the failedUrls and clear them?

**Review by d4rken — CHANGES_REQUESTED** [review]
Multithreading :cold_sweat:

**Comment by jakobmoellersap** [comment]
Too many open points, doing another approach with proper testing and reopening.

**Review by harambasicluka — DISMISSED** [review]
strings.xml look good.

File: Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt [hunk 3]
```diff
@@ -119,16 +125,29 @@ object RetrieveDiagnosisKeysTransaction : Transaction() {
...
+    private val progressTowardsQuotaForRollback = AtomicReference<Int>()
+
     private val transactionScope: TransactionCoroutineScope by lazy {
         AppInjector.component.transRetrieveKeysInjection.transactionScope
     }
 
+    private const val QUOTA_RESET_PERIOD_IN_HOURS = 24
+
+    private val quotaCalculator: QuotaCalculator<Int> = GoogleQuotaCalculator(
+        incrementByAmount = 14,
```
Comment (kbobrowski) [inline Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt:137]: Does it still increment count by 14 each time `executeAPISubmission` is called? I thought that after https://github.com/corona-warn-app/cwa-app-android/pull/1088 it should increment it only by 1, as `provideDiagnosisKeys` is called once. Assuming that Google docs are correct:

> Calls to this method are limited to six per day for token=TOKEN_A and 20 per day when token != TOKEN_A (Allowlisted accounts are allowed 1,000,000 calls per day.)
>
> This quota applies per call, not per file or batch of files uploaded. In other words, a single call with multiple files or multiple batches counts as only one call. Days are defined as midnight to midnight of a device's UTC.

**Review by d4rken — CHANGES_REQUESTED** [review]

File: Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt (hunk 3 above)
Comment (jakobmoellersap) [reply Corona-Warn-App/src/main/java/de/rki/coronawarnapp/transaction/RetrieveDiagnosisKeysTransaction.kt:137]: This will be done in a separate PR as we plan to provide this change here before 1.4 official release. this way we single out the commit. But you are correct, with the changes in v1.5 mode, this needs to be set to 1

File: Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/GoogleQuotaCalculator.kt [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+ * the start of the day in the given timeZone and Chronology
+ *
+ * @property incrementByAmount The amount of Quota Calls to increment per Call
+ * @property quotaLimit The maximum amount of Quota Calls allowed before Rate Limiting
+ * @property quotaResetPeriod The Period after which the Quota Resets
+ * @property quotaTimeZone The Timezone to work in
+ * @property quotaChronology The Chronology to work in
+ */
+class GoogleQuotaCalculator(
+    val incrementByAmount: Int,
```
[the remark this answers is not in the document]
Comment (jakobmoellersap) [reply Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/GoogleQuotaCalculator.kt:22]: kept in Favor of using it also in a check in resetProgressTowardsQuota

**Review by chris-cwa — APPROVED** [review]

**Review by d4rken — APPROVED** [review]
lgtm
