### PR TITLE
"Exposure check failed" without internet connection despite previous successful check (EXPOSUREAPP-13383)

### LINKED ISSUE #4740: Exposure Check Failed
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

There is a related issue in the FAQ: "Exposure Check Failed after updating to version 1.6.0", but I'm using 2.16.2.

## Technical details

- Device name: Nokia 7 plus
- Android version: 10
- App version: 2.16.2

## Describe the bug

For the 3rd or 4th day in a row I only get this message: "Exposure check failed" – "The synchronization of random IDs with the server failed. You can restart the synchronization manually." Tapping "Restart" shortly shows "Data is being downloaded" and "Check running", but then the status remains as before.

## Steps to reproduce the issue

Open the app and check the status page.

## Expected behaviour

I know that my status should be 'red' from a check-in last week.

## Possible Fix

-

## Additional context

Maybe this excerpt from the log helps? The date and time with high risk would match the event I checked into.

Possibly relevant: I forgot to check in when I entered the event, so I did it afterwards when I left and immediately checked out again. All people were still in the room (wearing masks, by the way), so I hadn't bothered updating the start time of the event until a few days ago when my status was either still green or already showed the error – I don't remember, unfortunately.

```
LastCombinedRiskResults(lastCalculated=CombinedEwPtRiskLevelResult(ptRiskLevelResult=PtRiskLevelResult(calculatedAt=2022-01-25T06:40:25.339Z, riskState=CALCULATION_FAILED, presenceTracingDayRisk=[PresenceTracingDayRisk(localDateUtc=2022-01-19, riskState=CALCULATION_FAILED)], checkInWarningOverlaps=[CheckInWarningOverlap(checkInId=31, transmissionRiskLevel=6, traceWarningPackageId=DE_456377, startTime=2022-01-19T19:05:17.458Z, endTime=2022-01-19T19:05:30.923Z)]), ewRiskLevelResult=RiskLevelTaskResult(calculatedAt=2022-01-25T06:40:28.179Z, failureReason=null, ewAggregatedRiskResult=EwAggregatedRiskResult(totalRiskLevel=HIGH, totalMinimumDistinctEncountersWithLowRisk=4, totalMinimumDistinctEncountersWithHighRisk=1, mostRecentDateWithLowRisk=2022-01-17T00:00:00.000Z, mostRecentDateWithHighRisk=2022-01-19T00:00:00.000Z, numberOfDaysWithLowRisk=1, numberOfDaysWithHighRisk=1, exposureWindowDayRisks=null), exposureWindows.size=null), exposureWindowDayRisks=[ExposureWindowDayRisk(dateMillisSinceEpoch=1642550400000, riskLevel=HIGH, minimumDistinctEncountersWithLowRisk=1, minimumDistinctEncountersWithHighRisk=1), ExposureWindowDayRisk(dateMillisSinceEpoch=1642377600000, riskLevel=LOW, minimumDistinctEncountersWithLowRisk=3, minimumDistinctEncountersWithHighRisk=0)]), lastSuccessfullyCalculated=CombinedEwPtRiskLevelResult(ptRiskLevelResult=PtRiskLevelResult(calculatedAt=2022-01-23T18:02:10.534Z, riskState=LOW_RISK, presenceTracingDayRisk=null, checkInWarningOverlaps=null),
```

---
Internal Tracking ID: [EXPOSUREAPP-11583](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11583)

### PR DESCRIPTION
**Pull request by mtwalli**
## Testing
- Follow the steps mentioned in the ticket.
- `Before` it shows failed risk calculation 
- `After` it shows low risk  

[Ticket](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13383)

### CODE REVIEW

**Comment by mtwalli** [comment]
Fixes: https://github.com/corona-warn-app/cwa-documentation/issues/800

**Review by CV113 — DISMISSED** [review]
UA approved

File: Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/storage/internal/RiskCombinator.kt [hunk 1]
```diff
@@ -75,7 +75,8 @@ class RiskCombinator @Inject constructor(
         val sortedEwResults = ewRiskResults.sortedByDescending { it.calculatedAt }
         return allDates.map { date ->
             val ptRisk = sortedPtResults.find {
-                it.calculatedAt <= date
+                // Consider only presence tracing "successful" risk calculation. See EXPOSUREAPP-13383
+                it.calculatedAt <= date && it.riskState != RiskState.CALCULATION_FAILED
```
Comment (mtwalli) [inline Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/storage/internal/RiskCombinator.kt:79]: this is the fix, rest is code cleanup and update failing tests

**Review by schauersbergern — APPROVED** [review]
