### PR TITLE
Double Timeout Variables for HTTP Requests and Triple the Timeout for the Transaction to ensure less timeouts are received with bad networking (EXPOSUREAPP-2190)

### LINKED ISSUE #998: [INFO] URSACHE: 9002, Etwas ist schiefgelaufen. Timeout
[INFO] CAUSE: 9002, Something went wrong. Time-out

Android 10 with 
Android Sicherheitsupdate / Security-Update: 1. Juli 2020
Nokia 7.1, Build: 00WW_4_15C_SP02
Internet: WLAN (only)
CWA-Version: 1.1.1

Das Problem trat heue erstmalig auf und war wiederholbar.
The problem performed for the first time today and was repeatable. 

Hier die Dokumentation...
Here the documentation...

1. Check-after-Start:
1  Check-after-Start

2. Error-Message:
2  Error-Message

3. Error-Message-Details:
3  Error-Message-Details

4. Display-after-Error (normal):
4  Display-after-Error (normal)

5. Additional-Info:
5  Additional-Info

Anmerkung: Diese Screen-Shots wurden beim 3. oder 4. Aufruf der CWA mit jeweils gleichem Verlauf / Fehlermeldungen erstellt.
Note: These screen shots were created with the 3rd or 4th call of the CWA with the same progression / error messages.

-----------
Update von heute Nachmittag...

Zusätzliche Information: Klickt man auf den Pfeil in Abbildung "4. Display-after-Error (normal)" passiert der gleiche Timeout nochmals (exakte Details konnte ich nicht vergleichen); "Prüfung läuft..."; siehe "6. Test-in-progress".

Beim Versuch diesen Vorgang ebenfalls inkl. der Details zu fotografieren, ereignete sich dieser Fehler nicht nochmals. 
Erstaunlich ist jedoch, dass die Angabe "Aktualisiert: Heute, 16:12" exakt 23 Stunden nach der vorherigen Aktualisierung stattfand; siehe Aktualisiert-Daten in "7. Your-Risk-Status" im Vergleich zu "4. Display-after-Error (normal)". 
D.h. der oben dokumentierte Fehler könnte mit dem Versuch der Aktualisierung innerhalb von 23:00 Stunden zusammenhängen. 23:00 Stunden (Heute: 16:12) nach der vorherigen Aktualisierung (Gestern: 17:12) trat der Fehler nicht mehr auf. 

Update from this afternoon ...

Additional information: If you click on the arrow in Figure "4. Display-after-Error (normal)", the same timeout happens again (I couldn't compare the exact details); "Prüfung läuft..."; see "6. Test in progress".

When trying to photograph this process including the details, this error did not occur again.
What is astonishing, however, is that the information "Updated: Today, 16:12" took place exactly 23 hours after the previous update; see updated data in "7. Your risk status" compared to "4. Display-after-Error (normal)".
I.e. the error documented above could be related to an attempt to update within 23:00 hours. 23:00 hours (today: 16:12) after the previous update (yesterday: 17:12) the error no longer occurred.

6. Test-in-progress:
6  Test-in-progress

Nach Abschluss der Prüfung wurde **vor** 16:12 Uhr der obige Fehler "Ursache: 9002 ... Timeout" angezeigt. (Das Foto entstand beim Versuch auch diesen Timeout zu dokumentieren, aber hier entstand der Fehler nicht mehr (16:12 Uhr).)
After completing the test, the above error "Cause: 9002 ... Timeout" was displayed **before** 4:12 pm. (The photo was taken while trying to document this timeout, but the error no longer occurred here (4:12 p.m.).)

7. Your-Risk-Status (Updated):
7  Your-Risk-Status

---
Internal Tracking ID: EXPOSUREAPP-2190

### PR DESCRIPTION
**Pull request by jakobmoellerdev**
This PR is done to ensure that we receive less Timeouts during bad networking or situations where the key retrieval takes longer. The PR can be tested by manually throttling the device network throughput and experiencing no timeout with HTTP Requests above 10 seconds and Transactions above 60s

### CODE REVIEW

File: Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/config/HTTPVariables.kt [hunk 1]
```diff
@@ -5,7 +5,7 @@ object HTTPVariables {
      * The maximal runtime of a transaction
      * In milliseconds
      */
-    private const val HTTP_CONNECTION_TIMEOUT = 10000L
+    private const val HTTP_CONNECTION_TIMEOUT = 20000L
```
Comment (harambasicluka) [inline Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/config/HTTPVariables.kt:8]: 20.000 ms are 0,33 mins. I thought we want to go from 1min to 2min?

**Review by chris-cwa — APPROVED** [review]
