### PR TITLE
No G status shown after grouping different names to one person (EXPOSUREAPP-12365)

### LINKED ISSUE #4959: v2.19.0: Vaccination status tag 2G+ gone
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy s10e
- Android version: 12
- App version: 2.19.0

## Describe the bug

I have 3 vaccination certificates:
image
All certificates have been created for the very same name. They were (and still are) grouped. There is no second certification group.

Before the update to v2.19, my certificate had the "2G+" tag.
Since the update, there is no tag at all:
image

App restart and phone restart did not help.

## Steps to reproduce the issue

1. Go to 'Certificates'
2. See that the tag is entirely missing.

## Expected behaviour

Show a tag for 2G+.

### LINKED ISSUE #4963: Vaccination certificates: the "Status Proof" ("Status-Nachweis") line may be missing after the allocation of certificates...

### PR DESCRIPTION
**Pull request by mtwalli**
##  To verify:
- Against `WRU`
- Scan in `2.18.0`

| Order | Certificate |
| ------ | ---------- |
|     1    | Screenshot 2022-03-19 at 11 55 24 |
| 2 | Screenshot 2022-03-19 at 11 56 25 |

- Upgrade to `2.19.0` 
  - The issue should occur
  - In this branch the issue should be resolved 

## Ticket
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12365

### CODE REVIEW

File: Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificates.kt [hunk 1]
```diff
@@ -41,6 +40,11 @@ data class PersonCertificates(
     }
 }
 
+/**
+ * First certificate identifier in the sorted certificates to insure consistency
+ */
+val Collection<CwaCovidCertificate>.identifier get() = toCertificateSortOrder().first().personIdentifier
```
Comment (mtwalli) [inline Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/core/PersonCertificates.kt:46]: Key change

**Review by BMItr — APPROVED** [review]
!lgtm

**Review by SamuraiKek — APPROVED** [review]
