### PR TITLE
Regression in date of birth formatting (EXPOSUREAPP-9297)

### LINKED ISSUE #4014: Regression in date of birth formatting
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue
Follow on report from https://github.com/corona-warn-app/cwa-app-android/issues/3963#issuecomment-911924812 and https://github.com/corona-warn-app/cwa-app-android/pull/3987

## Technical details

- Android version: 11
- App version: 2.10.0-RC2 (pre-release version)

## Describe the bug

PR https://github.com/corona-warn-app/cwa-app-android/pull/3987 has introduced a regression concerning inconsistent formatting regarding dates of birth.

For example, the date of birth in PersonDetailsFragment_cwa.png in release 2.10 should use the same order of month day year according to the English (United States) locale which is used in the date of sample on the same screen.

Instead of showing the date of birth as 1981/03/20, it should be shown as 03/20/1981. 

---
[PersonDetailsFragment_cwa from release/2.10.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.10.x)

PersonDetailsFragment_cwa_2 10_dates

---
[PersonDetailsFragment_cwa from screenshots 2.8](https://www.coronawarn.app/assets/screenshots/2-8/en/android/PersonDetailsFragment_cwa.png) for comparison. In this version the date formats were fixed and did not use the device's locale settings.

PersonDetailsFragment_cwa_2 8_dates

## Steps to reproduce the issue

1. Settings > System > Languages and input > Languages<br>set to English (United States)
2. Settings > System > Date & time<br>select "Use locale default"/ disable "Use 24-hour format"
3. Connect mobile device to Android Studio
4. In Android Studio Build > Select BuildVariant deviceForTestersDebug
5. run `src/androidTest/java/de/rki/coronawarnapp` on emulator
6. View > Tools Windows > Device File Explorer
7. Go to `/data/data/de.rki.coronawarnapp.test/screenshots`
8. View screenshots and check the formatting of all dates of birth

## Expected behavior

Dates of birth should be formatted according to the device's locale setting, except in certificates where a field label indicates formatting using YYYY-MM-DD. 

---
Internal Tracking ID: [EXPOSUREAPP-9297](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9297)

### PR DESCRIPTION
**Pull request by marcauberer**
Addresses [EXPOSUREAPP-9297](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9297)

The dob formatting now is 03/20/1981 instead of 1981/03/20.

### CODE REVIEW

File: Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/CwaUserCard.kt [hunk 1]
```diff
@@ -47,7 +47,9 @@ class CwaUserCard(parent: ViewGroup) :
                 .find { char -> !Character.isDigit(char) }
                 .toString()
             when (delimiter) {
-                "/" -> dateOfBirthFormatted.split("-").joinToString(delimiter)
+                "/" -> dateOfBirthFormatted.split("-").run {
+                    listOf(this[1], this[2], this[0])
```
Comment (mtwalli) [inline Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/CwaUserCard.kt:51]: it is not always 3 elements , it could be 2 only. I suggest to use `getOrNull(index)` 
```kotlin
listOfNotNull(getOrNull[1], getOrNull[2], getOrNull[0])
```

**Comment by MikeMcC399** [comment]
@marcauberer / @mtwalli 

It seems that PR https://github.com/corona-warn-app/cwa-app-android/pull/3988 "Booster Vaccination (EXPOSUREAPP-8718)" which is a major feature commit from `feature/8718-booster-vaccination` has broken `PersonDetailsFragmentTest.kt` in [release/2.10.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.10.x) and (since this is also merged into [fix/dob-regression](https://github.com/corona-warn-app/cwa-app-android/tree/fix/dob-regression)) in https://github.com/corona-warn-app/cwa-app-android/pull/4036 as well.

Test results attached:

[Test Results - PersonDetailsFragmen___.zip](https://github.com/corona-warn-app/cwa-app-android/files/7127157/Test.Results.-.PersonDetailsFragmen___.zip)

File: Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/CwaUserCard.kt (hunk 1 above)
Comment (marcauberer) [reply Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/person/ui/details/items/CwaUserCard.kt:51]: Oh yes, already forgot about that again, thanks 😅

**Comment by mtwalli** [comment]
> @marcauberer / @mtwalli
> 
> It seems that PR #3988 "Booster Vaccination (EXPOSUREAPP-8718)" which is a major feature commit from `feature/8718-booster-vaccination` has broken `PersonDetailsFragmentTest.kt` in [release/2.10.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.10.x) and (since this is also merged into [fix/dob-regression](https://github.com/corona-warn-app/cwa-app-android/tree/fix/dob-regression)) in #4036 as well.
> 
> Test results attached:
> 
> [Test Results - PersonDetailsFragmen___.zip](https://github.com/corona-warn-app/cwa-app-android/files/7127157/Test.Results.-.PersonDetailsFragmen___.zip)

@MikeMcC399  this issue should be fixed by: https://github.com/corona-warn-app/cwa-app-android/pull/4041

**Comment by MikeMcC399** [comment]
@mtwalli
> > It seems that PR #3988 "Booster Vaccination (EXPOSUREAPP-8718)" which is a major feature commit from `feature/8718-booster-vaccination` has broken `PersonDetailsFragmentTest.kt` in [release/2.10.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.10.x) and (since this is also merged into [fix/dob-regression](https://github.com/corona-warn-app/cwa-app-android/tree/fix/dob-regression)) in #4036 as well.
> > Test results attached:
> > [Test Results - PersonDetailsFragmen___.zip](https://github.com/corona-warn-app/cwa-app-android/files/7127157/Test.Results.-.PersonDetailsFragmen___.zip)
> 
> @MikeMcC399 this issue should be fixed by: #4041

#4041 does fix the issue with `PersonDetailsFragmentTest.kt` I mentioned, however when trying to run the full `androidTest` set to generate a complete set of screenshots, the tests now fail at `RecoveryCertificateDetailFragmentTest.kt` instead. There may be other tests which would also fail, so fixing test modules should continue until all tests run successfully.

**Comment by mtwalli** [comment]
> @mtwalli
> 
> > > It seems that PR #3988 "Booster Vaccination (EXPOSUREAPP-8718)" which is a major feature commit from `feature/8718-booster-vaccination` has broken `PersonDetailsFragmentTest.kt` in [release/2.10.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.10.x) and (since this is also merged into [fix/dob-regression](https://github.com/corona-warn-app/cwa-app-android/tree/fix/dob-regression)) in #4036 as well.
> > > Test results attached:
> > > [Test Results - PersonDetailsFragmen___.zip](https://github.com/corona-warn-app/cwa-app-android/files/7127157/Test.Results.-.PersonDetailsFragmen___.zip)
> > 
> > 
> > @MikeMcC399 this issue should be fixed by: #4041
> 
> #4041 does fix the issue with `PersonDetailsFragmentTest.kt` I mentioned, however when trying to run the full `androidTest` set to generate a complete set of screenshots, the tests now fail at `RecoveryCertificateDetailFragmentTest.kt` instead. There may be other tests which would also fail, so fixing test modules should continue until all tests run successfully.

@MikeMcC399  I will check them, but it does not prevent you from reviewing this issue here ,right? 
Can you verify the fix here is covering the issue of formatting the date ?

**Comment by MikeMcC399** [comment]
@mtwalli 
> I will check them, but it does not prevent you from reviewing this issue here ,right?
Can you verify the fix here is covering the issue of formatting the date ?

I was intending to verify the fix by generating a complete set of screenshots and then checking the dates in all the screenshots.

I can't do that unless screenshot generation works properly. The failing `RecoveryCertificateDetailFragmentTest.kt` for instance generates a screenshot which includes a date of birth, which I can't therefore check.

**Comment by MikeMcC399** [comment]
@mtwalli 
Would you prefer me to open a separate issue about the failure to generate screenshots in the current release/2.10.x branch so that it can be handled separately?

**Review by MikeMcC399 — APPROVED** [review]
@mtwalli 

I reviewed issue https://github.com/corona-warn-app/cwa-app-android/issues/4014 and in fact only the screenshots
`PersonDetailsFragment*.png` were affected.

Since I could regenerate these screenshots with
`Run PersonDetailsFragmentTest.kt`
from the branch for this PR I was able to verify the fix is correct.

I don't have the means to verify for contracted dates of birth like
YYYY only and
YYYY-MM
The screenshots only use full dates of birth where all fields YYYY, MM and DD are populated.

So from my point of view the issue is now fixed.

Thank you!

**Comment by mtwalli** [comment]
> Would you prefer me to open a separate issue about the failure to generate screenshots in the current release/2.10.x branch so that it can be handled separately?

@MikeMcC399  No need for issue , here is a PR https://github.com/corona-warn-app/cwa-app-android/pull/4043

**Review by mtwalli — APPROVED** [review]
LGTM, Thanks @marcauberer  for taking for it. Thanks @MikeMcC399  for reporting and verifying the fix
