### PR TITLE
Reverse order of Transmission Risk Levels used for Diagnosis Keys Upload (closes #678)

### LINKED ISSUE #678: Diagnosis Keys Upload: Transmission Risk Levels are applied in reverse order
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only - I think so, on iOS the [sort order](https://github.com/corona-warn-app/cwa-app-ios/blob/5618da6fc3faa4ecef3a6763250230501fae3774/src/xcode/ENA/ENA/Source/Services/ExposureSubmissionService.swift#L207) seems to be correct.
* [x] Bug is not already reported in another issue (at least I didn't find it)

## Describe the bug

The "Epidemiological Motivation of the Transmission Risk Level" [document](https://github.com/corona-warn-app/cwa-documentation/blob/master/transmission_risk.pdf) gives the "Transmission risk level for the Base Case" (Figure 14) as **5, 6, 8, 8, 8, 5, 3, 1, 1, 1, 1, ...** for values 0..13 of _Delay from Exposure to Consent for Upload_. This is counting backwards, 0 (today) should be assigned **5**, 1 (yesterday) should be assigned **6**, and so on.

However, `fun List<TemporaryExposureKey>.transformKeyHistoryToExternalFormat()` [(link)](https://github.com/corona-warn-app/cwa-app-android/blob/c2e5bd49093193060dded4d1545f783a498a96da/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ProtoFormatConverterExtensions.kt#L35) assigns these values the other way around: The key with the _lowest_ `rollingStartIntervalNumber`, i.e. the _oldest_ key is assigned **6** (**5** as the value for today is ignored, because the API doesn't provide today's key), and so on.

## Expected behaviour

The risk levels should be applied as explained in the "Epidemiological Motivation of the Transmission Risk Level" document, not the other way around, because then risk levels would make no sense. (This is not extremely critical in the beginning of the roll-out, when users have only 6 keys to upload, as the curve is quite symmetrical on the left end, but will cause nonsense risk estimations once users have all 14 keys saved on their device.) 

## Possible Fix

I plan to provide a Pull Request with a fix and a test case for the function.

### PR DESCRIPTION
**Pull request by mh-**
## Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] If this PR comes from a fork, please [Allow edits from maintainers](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
* [x] Set a speaking title. Format: {task_name} (closes #{issue_number}). For example: Use logger (closes # 41)
* [x] [Link your Pull Request to an issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) (if applicable)
* [ ] Create Work In Progress [WIP] pull requests only if you need clarification or an explicit review before you can continue your work item.
* [x] Make sure that your PR is not introducing _unnecessary_ reformatting (e.g., introduced by on-save hooks in your IDE)
* [x] Make sure that your PR does not contain changes in text files, therefore the PR must not contain changes in values/strings/* and / or assets/* (see issue #332 for further information)
* [x] Make sure that your PR does not contain compiled sources (already set by the default .gitignore) and / or binary files

## Description

Fixes https://github.com/corona-warn-app/cwa-app-android/issues/678

### CODE REVIEW

File: Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ProtoFormatConverterExtensions.kt [hunk 1]
```diff
@@ -33,9 +33,9 @@ object ProtoFormatConverterExtensions {
         this.sortedWith(compareBy { it.rollingStartIntervalNumber }).asReversed().take(MAXIMUM_KEYS)
 
     fun List<TemporaryExposureKey>.transformKeyHistoryToExternalFormat() =
-        this.sortedWith(compareBy { it.rollingStartIntervalNumber })
+        this.sortedWith(compareBy { it.rollingStartIntervalNumber }).asReversed()
```
Comment (ChristopherSchmitz) [inline Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ProtoFormatConverterExtensions.kt:36]: @mh- next to the asReversed option I see the other option to use "compareByDescending" instead of "compareBy". This option would result into better readability of code.

Do you see anything speaking against the usage of "compareByDescending"? (for sure we remove as Reversed in all the places)

Comment (mh-) [reply Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ProtoFormatConverterExtensions.kt:36]: @ChristopherSchmitz `compareByDescending` is probably better, if it makes the code more readable. I don't read Kotlin a lot and indeed had a hard time understanding the code. So I just copied the pattern from [.limitKeyCount()](https://github.com/corona-warn-app/cwa-app-android/blob/c2e5bd49093193060dded4d1545f783a498a96da/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ProtoFormatConverterExtensions.kt#L33) and wrote a test case to see what it's actually doing. 
The test case assumes that the keys are ordered chronologically, but if that's not required for upload to the server, we could also move the 2nd sorting to the test.
Not sure how you prefer to proceed? Do you want to edit the PR, or should I do it?

Comment (ChristopherSchmitz) [reply Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ProtoFormatConverterExtensions.kt:36]: @mh since we use on iOS a desc order when submitting to the server I would keep the behaviour consistent.
If you like to adjust your PR this would be wonderful. We plan to close and merge this in the next 2 hours :-)

Comment (mh-) [reply Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ProtoFormatConverterExtensions.kt]: @ChristopherSchmitz done.

**Review by ChristopherSchmitz — APPROVED** [review]
@mh- many thanks for your support! This looks really good.

**Review by jakobmoellerdev — APPROVED** [review]
